Update LM-Eval with PVC example
trustyai-explainability/trustyai-explainability.github.io pull request #35
Opened 2024-10-29 09:35 UTC by ruivieira

2024-10-29 13:43 UTC, christinaexyou commented
* Fix typo in line 201. Should be logSamples

Apart from that lgtm

2024-10-29 13:45 UTC, christinaexyou requested changes
Fix typo in line 201. Should be logSamples. Apart from that lgtm !

2024-10-30 10:55 UTC, ruivieira commented
@christinaexyou fixed, thanks!

2024-10-30 10:56 UTC, RobGeada approved these changes

2024-10-30 13:32 UTC, christinaexyou approved these changes

2024-10-30 15:29 UTC, merged